#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker { image 'node:16.13.1-alpine' }
            }
            steps {
                sh "npm install typescript"
            }
        }
    }
}